### ISSUE TITLE
Quantum Break unpacked exe crash

### ISSUE THREAD

**Issue by krystiangorecki** [atom0s/Steamless#105] opened 2023-09-09 13:21 UTC
https://store.steampowered.com/app/474960/Quantum_Break/

Exe unpacks without any errors but the game doesn't start. Screen goes black and after 1 second it's back to the Desktop. I tried selecting and deselecting all options.

It used to be possible to unpack this game as some resolution and aspect ratio patch relies on Steamless: https://www.wsgf.org/phpBB3/viewtopic.php?f=95&t=30963#p175748

![Screenshot_69](https://github.com/atom0s/Steamless/assets/10375973/0183d8c2-28ca-4162-a59c-d0bbe7768d5f)

**Comment by atom0s** [comment] 2023-09-12 06:49
> Exe unpacks without any errors but the game doesn't start. Screen goes black and after 1 second it's back to the Desktop. I tried selecting and deselecting all options.

This sounds like Steamless properly unpacked the file but something else on your end is causing it to crash. Generally, if Steamless fails to properly unpack a file, then the file won't even attempt to start or show any kind of activity.

Instead, the application will instead do something such as:

  - Instantly crash silently. (Usually will cause a crash dump to happen if your system has it enabled.)
  - Instantly crash and display a Windows error code.
  - Fail to start at all, causing a Windows error stating the application is invalid.
  - Fail to start at all, causing a Windows error stating the application has been tampered with in some manner.

Since you are unpacking the file inside of its original directory, I would suggest doing the following:

  - Rename the real/original `QuantumBreak.exe` to something like: `QuantumBreak_original.exe`
  - Use Steamless to unpack: `QuantumBreak_original.exe`
  - Rename the unpacked file to: `QuantumBreak.exe`

Some games require/expect the original file name in order to locate the proper files needed to load.

**Comment by GallsVital** [comment] 2024-01-12 21:18
> > Exe unpacks without any errors but the game doesn't start. Screen goes black and after 1 second it's back to the Desktop. I tried selecting and deselecting all options.
> 
> This sounds like Steamless properly unpacked the file but something else on your end is causing it to crash. Generally, if Steamless fails to properly unpack a file, then the file won't even attempt to start or show any kind of activity.
> 
> Instead, the application will instead do something such as:
> 
> * Instantly crash silently. (Usually will cause a crash dump to happen if your system has it enabled.)
> * Instantly crash and display a Windows error code.
> * Fail to start at all, causing a Windows error stating the application is invalid.
> * Fail to start at all, causing a Windows error stating the application has been tampered with in some manner.
> 
> Since you are unpacking the file inside of its original directory, I would suggest doing the following:
> 
> * Rename the real/original `QuantumBreak.exe` to something like: `QuantumBreak_original.exe`
> * Use Steamless to unpack: `QuantumBreak_original.exe`
> * Rename the unpacked file to: `QuantumBreak.exe`
> 
> Some games require/expect the original file name in order to locate the proper files needed to load.

Tried all of the above but it simply does not work. Black screen -> crash. Windows event viewer shows the following info for the crash:
```

Faulting application name: QuantumBreak.exe, version: 0.0.0.0, time stamp: 0x5808b16e
Faulting module name: renderer_x64_f.dll, version: 0.0.0.0, time stamp: 0x5808affa
Exception code: 0xc0000005
Fault offset: 0x0000000000226f37
Faulting process ID: 0x0x1004
Faulting application start time: 0x0x1DA45858A9F7CCE
Faulting application path: G:\SteamLibrary\steamapps\common\QuantumBreak\dx11\QuantumBreak.exe
Faulting module path: G:\SteamLibrary\steamapps\common\QuantumBreak\dx11\renderer_x64_f.dll
Report ID: bc412b0e-5f5e-4e5d-b266-4328ec57e16a
Faulting package full name: 
Faulting package-relative application ID: 
```

Literally nothing else has changed, the old unmodified exe still works just fine.

**Comment by GallsVital** [comment] 2024-01-12 21:44
> > > Exe unpacks without any errors but the game doesn't start. Screen goes black and after 1 second it's back to the Desktop. I tried selecting and deselecting all options.
> > 
> > 
> > This sounds like Steamless properly unpacked the file but something else on your end is causing it to crash. Generally, if Steamless fails to properly unpack a file, then the file won't even attempt to start or show any kind of activity.
> > Instead, the application will instead do something such as:
> > 
> > * Instantly crash silently. (Usually will cause a crash dump to happen if your system has it enabled.)
> > * Instantly crash and display a Windows error code.
> > * Fail to start at all, causing a Windows error stating the application is invalid.
> > * Fail to start at all, causing a Windows error stating the application has been tampered with in some manner.
> > 
> > Since you are unpacking the file inside of its original directory, I would suggest doing the following:
> > 
> > * Rename the real/original `QuantumBreak.exe` to something like: `QuantumBreak_original.exe`
> > * Use Steamless to unpack: `QuantumBreak_original.exe`
> > * Rename the unpacked file to: `QuantumBreak.exe`
> > 
> > Some games require/expect the original file name in order to locate the proper files needed to load.

Managed to fix it by checking the option to keep the .bind section in the file, since there were indications that there was other DRM at play and the presence of steamapi-files. Then it works to launch the game through Steam as I normally would. Ultrawide patch works again!

Edit: Oh, and I altered the hex values manually - not sure if the patcher still works. Replace 26 B4 17 att 00B0F590  with AB AA AA.

**Comment by atom0s** [comment] 2024-01-16 01:49
I am going to assume the reported crashes are due to additional modifications or proxies being used with the game. I cannot reproduce any crash after unpacking the game personally. Fresh download and install of the game _(version `1.0.126.0307` as of this post)_ and it works perfectly fine.

Marking this as closed / not a bug since local testing shows it works fine.

**Closed as completed by atom0s** 2024-01-16 01:49 UTC
Labels: p: low, s: not a bug, t: question, c: general
