### ISSUE TITLE
This worked for me, but I have a few questions about reliability.

### ISSUE THREAD

**Issue by ancient-animal** [atom0s/Steamless#38] opened 2020-08-13 18:38 UTC
I own a game on Steam, and this program worked for me. (I used version 3.0.0.9)

I quickly tested the game with the new executable file and it worked, but I have a few concerns.

1:
Could this possibly cause glitches that are hard to notice? I mean, imagine that I play 20 hours of a game with the EXE file produced by Steamless. Could a glitch appear later as a result of using this new EXE file, or is it 100 percent as reliable as using the official EXE file from Steam?

2:
Is Steamless so perfect that I would be wasting money by buying the GOG version of the game? If the creator of Steamless says that some unwanted and unforeseen problems could be caused by using an executable file produced by Steamless, I'll buy the GOG version, but if the Steamless procedure is guaranteed to be flawless, I'll save money.

Full Disclosure: some of the problems mentioned in various comments in the Issue Tracker scared me, but I don't understand them, so I would like some reassurance.

**Comment by OdinVex** [comment] 2020-08-13 19:16
> I own a game on Steam, and this program worked for me. (I used version 3.0.0.9)
> 
> I quickly tested the game with the new executable file and it worked, but I have a few concerns.
> 
> 1:
> Could this possibly cause glitches that are hard to notice? I mean, imagine that I play 20 hours of a game with the EXE file produced by Steamless. Could a glitch appear later as a result of using this new EXE file, or is it 100 percent as reliable as using the official EXE file from Steam?
> 
> 2:
> Is Steamless so perfect that I would be wasting money by buying the GOG version of the game? If the creator of Steamless says that some unwanted and unforeseen problems could be caused by using an executable file produced by Steamless, I'll buy the GOG version, but if the Steamless procedure is guaranteed to be flawless, I'll save money.
> 
> Full Disclosure: some of the problems mentioned in various comments in the Issue Tracker scared me, but I don't understand them, so I would like some reassurance.

As for #1... If a game does not in any way use Steam DRM other than to protect itself, it won't be a problem.

As for #2... Steamless is practically as well rounded as possible. Some games however walk through their PE32 sections and validate them or go out of their way to use the .bind section in cryptographic routines. Rare but has happened.

I personally support GOG, if they have what I want at an honest price. I'm no thief. If in doubt, be honest and buy it at an honest price anyway. It's not like Steamless is meant to pirate games (although that is probably majority use)... I've modified Steamless myself just to fix up executables after I've manually removed SteamDRM myself just because I don't want a game attached to Steam.

Recommend closing Issue, I think I've covered it for the most part.

**Comment by atom0s** [comment] 2020-08-13 21:27
> 1:
Could this possibly cause glitches that are hard to notice? I mean, imagine that I play 20 hours of a game with the EXE file produced by Steamless. Could a glitch appear later as a result of using this new EXE file, or is it 100 percent as reliable as using the official EXE file from Steam?

Generally no, however, games can add extra layers of security or validation to ensure it has not been tampered with. An example of this would be the early versions of Grim Dawn. They would detect if the .bind section was removed and cause the game to not progress properly. (Keeping the bind section would fix the issues.) I would never personally say anything is 100% reliable. There is always room for things to break/not work as expected and given that developers can add their own extra detection/security measures, there are chances of failure.

> 2:
Is Steamless so perfect that I would be wasting money by buying the GOG version of the game? If the creator of Steamless says that some unwanted and unforeseen problems could be caused by using an executable file produced by Steamless, I'll buy the GOG version, but if the Steamless procedure is guaranteed to be flawless, I'll save money.

Again, I don't consider anything perfect. Always use anything with caution, and understand there are no guarantees. 

Moneywise, purchase games always. Developers need the support to continue making their games and I do not condone piracy or assist with it with my tools. Where you buy the game from is ultimately up to you. GOG is fine if the game is available there, Steam otherwise. I wouldn't recommend stores like Epic's given the majority ownership being Tencent/China. 

> Full Disclosure: some of the problems mentioned in various comments in the Issue Tracker scared me, but I don't understand them, so I would like some reassurance.

Over the years, there has been 3 'major' revisions of SteamStub (v1, v2, v3; although we have no guarantee on the actual naming) with a bunch of mini-updates in-between each one. Some versions altered support for various things, added new features, removed old features, changed how certain parts worked etc. so it takes time to collect samples of all possible instances of the protection to get things fixed. Most issues that get opened for something not working are generally due to a version that was not currently supported.

**Closed as completed by atom0s** 2020-08-13 21:27 UTC
Labels: s: not a bug, t: question, c: general

**Comment by ancient-animal** [comment] 2020-08-13 21:35
I appreciate your answers.

Just to be clear, I paid full price for the Steam version. I just didn't want to pay for the same game again to get a version without DRM. I'll buy the GOG version in case the creators hid some type of personal detection method later in the game. My reasons are solely to avoid leaving Steam open plus for preservation of old versions in case newer versions have worse glitches than older versions.

Thanks.
